/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-02-28 17:47:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import conn.db.DBconnect;
import java.sql.Connection;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/component/navbar.jsp", Long.valueOf(1740677138913L));
    _jspx_dependants.put("/component/css.jsp", Long.valueOf(1740389687291L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("conn.db.DBconnect");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Index Page</title>\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\"\n");
      out.write("	integrity=\"sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==\"\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\n");
      out.write("	crossorigin=\"anonymous\"></script>");
      out.write("\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".paint-card {\n");
      out.write("	box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.3);\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\n");
      out.write("	<div class=\"container-fluid\">\n");
      out.write("		<a class=\"navbar-brand\" href=\"index.jsp\"><i\n");
      out.write("			class=\"fas fa-clinic-medical\"></i> We Help </a>\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("			data-bs-target=\"#navbarSupportedContent\"\n");
      out.write("			aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("			aria-label=\"Toggle navigation\">\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("		</button>\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("			<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\n");
      out.write("				\n");
      out.write("					\n");
      out.write("\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\"\n");
      out.write("						aria-current=\"page\" href=\"userlogin.jsp\">USER</a></li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\"\n");
      out.write("						aria-current=\"page\" href=\"adminlogin.jsp\"><i \n");
      out.write("						class=\"fas fa-sign-in-alt\"></i> ADMIN</a></li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\"\n");
      out.write("										aria-current=\"page\" href=\"doctorlogin.jsp\"><i\n");
      out.write("						class=\"fas fa-sign-in-alt\"></i> DOCTOR</a></li>\n");
      out.write("			\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("	\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div id=\"carouselExampleIndicators\" class=\"carousel slide\"\n");
      out.write("		data-bs-ride=\"carousel\">\n");
      out.write("		<div class=\"carousel-indicators\">\n");
      out.write("			<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\n");
      out.write("				data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\"\n");
      out.write("				aria-label=\"Slide 1\"></button>\n");
      out.write("			<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\n");
      out.write("				data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\n");
      out.write("			<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\n");
      out.write("				data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"carousel-inner\">\n");
      out.write("			<div class=\"carousel-item active\">\n");
      out.write("				<img src=\"image/ind.jpg\" class=\"d-block w-100\" alt=\"...\"\n");
      out.write("					height=\"500px\">\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"container p-3\">\n");
      out.write("		<p class=\"text-center fs-2 \">About  our Hospital</p>\n");
      out.write("\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-md-8 p-5\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-6\">\n");
      out.write("						<div class=\"card paint-card\">\n");
      out.write("							<div class=\"card-body\">\n");
      out.write("								<p class=\"fs-5\">100% Time-Saving</p>\n");
      out.write("								<p>Our online booking system eliminates the need for time-consuming phone calls or visits to your doctor's office. You can easily book, cancel or reschedule your appointment anytime, anywhere.</p>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-md-6\">\n");
      out.write("						<div class=\"card paint-card\">\n");
      out.write("							<div class=\"card-body\">\n");
      out.write("								<p class=\"fs-5\">Flexible Options</p>\n");
      out.write("								<p>Our system provides you with a range of options to suit your needs. You can choose the doctor you want to see, select the type of appointment, and even specify the reason for your visit.</p>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-md-6 mt-2\">\n");
      out.write("						<div class=\"card paint-card\">\n");
      out.write("							<div class=\"card-body\">\n");
      out.write("								<p class=\"fs-5\">Customizable Features</p>\n");
      out.write("								<p>We understand that every patient's needs are unique, so our system allows you to customize your appointments to suit your requirements. You can add notes or special requests, and even request a telemedicine appointment if you prefer.</p>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-md-6 mt-2\">\n");
      out.write("						<div class=\"card paint-card\">\n");
      out.write("							<div class=\"card-body\">\n");
      out.write("								<p class=\"fs-5\">Secure and Confidential</p>\n");
      out.write("								<p>Our online system uses state-of-the-art security measures to ensure the confidentiality of your personal information. You can be confident that your data is safe and protected at all times</p>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"col-md-4\">\n");
      out.write("				<img alt=\"\" src=\"image/acc1.svg\" class=\"img-fluid\" width=\"400px\" height=\"600px\">\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<hr>\n");
      out.write("\n");
      out.write("	\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
